AWSTemplateFormatVersion: '2010-09-09'
Description: Configuración de Kinesis Firehose para la ingesta de datos hacia S3 usando LabRole.

Parameters:
  BaseStackName:
    Type: String
    Default: p5-base-stack
    Description: Nombre del primer stack (el que contiene el Bucket y el Stream).

Resources:

  
  DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: EventToS3Firehose
      DeliveryStreamType: KinesisStreamAsSource
      
      KinesisStreamSourceConfiguration:
        
        KinesisStreamARN: !Sub 
          - "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${StreamName}"
          - StreamName: 
              Fn::ImportValue: !Sub "${BaseStackName}-KinesisStreamName"
        # Usamos el LabRole existente ya que no podemos crear roles nuevos
        RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      
      S3DestinationConfiguration:
        # Importamos el nombre del bucket desde el Stack base
        BucketARN: !Sub 
          - "arn:aws:s3:::${BucketName}"
          - BucketName: 
              Fn::ImportValue: !Sub "${BaseStackName}-BucketName"
              
        RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
        
        
        Prefix: "raw/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/"
        ErrorOutputPrefix: "errors/!{firehose:error-output-type}/year=!{timestamp:yyyy}/month=!{timestamp:MM}/"
        
        # Optimización de Buffering
        BufferingHints:
          IntervalInSeconds: 60 # Cada 60 segundos
          SizeInMBs: 1          # 1 MB para poder ver los datos rápidamente en S3 durante la prueba, que si no nos pegamos vida y media
        
        # Esto realmente no es necesario, basicamente comprime los datos al guardarlos en S3 ahorrando espacio, pero bueno tampoco esta de mas
        CompressionFormat: GZIP

Outputs:
  FirehoseArn:
    Description: ARN del Delivery Stream de Firehose
    Value: !GetAtt DeliveryStream.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FirehoseArn"